name: Deploy to Cloudflare Pages

env:
  PROJECT_NAME: calculator
  STATIC_ASSETS_DIR: dist

on:
  push:
    branches:
      - main
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # 前のコミットと比較するために必要
      - name: Check version change
        id: version-check
        run: |
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r .version 2>/dev/null)
          NEW_VERSION=$(jq -r .version package.json 2>/dev/null)
          if [ "$PREVIOUS_VERSION" == "$NEW_VERSION" ]; then
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Skip deployment if version is not changed
        if: steps.version-check.outputs.version_changed != 'true'
        run: |
          echo "⏭️ バージョンが変更されていないため、デプロイをスキップします"
          exit 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Build
        run: bun install && bun run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.STATIC_ASSETS_DIR }} --project-name=${{ env.PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
